version: '3.4'

services:
  # NGINX service
  nginx:
    image: nginx:1.15.5-alpine
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './:/app'
    ports:
      - '8081:80'

  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: docker/php/dockerfile
      target: php
    volumes:
      - './:/app'
      - './docker/php/fpm.conf:/usr/local/etc/php-fpm.conf:ro'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini:ro'

  # MYSQL service
  mysql:
    image: mysql:5.7

    environment:
    - MYSQL_DATABASE=camphero
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'db:/var/lib/mysql'

volumes:
  # DB save
  db: {}
